# Backend configuration for remote state storage
# This configuration uses partial configuration
# Values are provided via backend.tfbackend file generated by deploy.sh
# 
# To manually configure:
#   terraform init -backend-config=backend.tfbackend
# Or with individual parameters:
#   terraform init -backend-config="bucket=<bucket-name>" \
#                  -backend-config="dynamodb_table=<table-name>"

terraform {
  backend "s3" {
    # Partial backend configuration
    # Actual values provided via backend.tfbackend or -backend-config flags
    key     = "dev/terraform.tfstate"
    encrypt = true
  }
}